name: Autoapprove and Automerge

on:
  pull_request:
  
jobs:
  automerge-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Pull Request Number
        id: pr
        uses: actions/github-script@v5
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              throw new Error("Event payload missing pull request number.");
            }
            return pr.number;

      - name: Auto Merge Pull Request
        uses: "pascalgn/automerge-action@v0.16.2"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}