name: Print Secrets
#on:
#  schedule:
#    - cron: '0 12 * * 1'
on: [workflow_dispatch]
jobs:
  rotate:
    name: rotate gcp key
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          DEBUG_SECRET_KEY: ${{ secrets.GCP_SA_INFRA_KEY }}
        run: |
          echo $DEBUG_SECRET_KEY >> secrets.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
        timeout-minutes: 15
